# Generated by Django 4.0.4 on 2022-07-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0002_order_orderitems_precios_unidadmedida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria_usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='precios',
            name='tipo_usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiambres.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='unidadmedida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fiambres.unidadmedida'),
        ),
    ]
