# Generated by Django 4.0.4 on 2022-07-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('fiambres', '0004_alter_product_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
    ]
