# Generated by Django 4.0.4 on 2022-07-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0005_alter_product_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidadmedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiambres.unidadmedida'),
        ),
    ]
