# Generated by Django 4.0.4 on 2022-07-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0006_alter_product_unidadmedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factura',
            field=models.ImageField(blank=True, upload_to='facturas/'),
        ),
    ]
